"""agregar_descubrimientos_a_informes

Revision ID: 65dbbe53a9ec
Revises: 0de3166bd3b0
Create Date: 2026-07-16 04:12:59.540215+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '65dbbe53a9ec'
down_revision: Union[str, None] = '0de3166bd3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###