"""agregar_recomendaciones_inteligentes_a_informes

Revision ID: 0410b147e0fd
Revises: 1b2122a8324e
Create Date: 2026-07-23 18:28:44.615898+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0410b147e0fd'
down_revision: Union[str, None] = '1b2122a8324e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###