"""agregar_descubrimientos_a_informes

Revision ID: 0813e6f13aea
Revises: 65dbbe53a9ec
Create Date: 2026-07-16 04:45:31.864127+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0813e6f13aea'
down_revision: Union[str, None] = '65dbbe53a9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###