"""agregar_recomendaciones_inteligentes_a_informes

Revision ID: 1b2122a8324e
Revises: 1425488ed816
Create Date: 2026-07-23 18:12:01.957069+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1b2122a8324e'
down_revision: Union[str, None] = '1425488ed816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informes', sa.Column('recomendaciones_inteligentes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('informes', 'recomendaciones_inteligentes')
    # ### end Alembic commands ###