"""agregar_interpretacion_profesional_a_informes

Revision ID: f02d7e7aa03d
Revises: 0813e6f13aea
Create Date: 2026-07-23 02:55:37.030045+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f02d7e7aa03d'
down_revision: Union[str, None] = '0813e6f13aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informes', sa.Column('interpretacion_profesional', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('informes', 'interpretacion_profesional')
    # ### end Alembic commands ###