"""agregar_interpretacion_profesional_a_informes

Revision ID: 1425488ed816
Revises: f02d7e7aa03d
Create Date: 2026-07-23 03:07:54.802260+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1425488ed816'
down_revision: Union[str, None] = 'f02d7e7aa03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###