"""agregar_visualizaciones_inteligentes_a_informes

Revision ID: df0d72340336
Revises: 0410b147e0fd
Create Date: 2026-07-24 03:34:16.765015+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df0d72340336'
down_revision: Union[str, None] = '0410b147e0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informes', sa.Column('visualizaciones_inteligentes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('informes', 'visualizaciones_inteligentes')
    # ### end Alembic commands ###