"""agregar_visualizaciones_inteligentes_a_informes

Revision ID: 7ac38c3c0baf
Revises: df0d72340336
Create Date: 2026-07-24 04:17:53.373243+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7ac38c3c0baf'
down_revision: Union[str, None] = 'df0d72340336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###