"""agregar_descubrimientos_a_informes

Revision ID: 0de3166bd3b0
Revises: 970fd31264a6
Create Date: 2026-07-16 03:23:09.086621+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0de3166bd3b0'
down_revision: Union[str, None] = '970fd31264a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informes', sa.Column('descubrimientos', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('informes', 'descubrimientos')
    # ### end Alembic commands ###